version: '3.7'

services:
  # PostgreSQL
  postgres:
    image: postgres:12
    environment:
        POSTGRES_USER: postgresdev
        POSTGRES_PASSWORD: postgresdev
        POSTGRES_DB: rootmoney
    ports:
      - "5432:5432"
    container_name: postgredb
    volumes:
      - dbdata:/var/lib/postgresql/data

#Volumes
volumes:
  dbdata:
    driver: local